name: env_zoo_calrissian
channels:
  - terradue
  - conda-forge
  - eoepca
dependencies:
  - python==3.10
  - black
  - pre-commit
  - isort
  - flake8
  - autoflake
  - pylint
  - nose2
  - git
  - pip
  - cwl-wrapper
  - pycalrissian
  - loguru
  - pip:
    - git+https://github.com/gusbru/zoo-calrissian-runner.git@test
    - git+ssh://git-codecommit.us-east-1.amazonaws.com/v1/repos/ades_v2.git@main
    - attrs
    - cwl-utils==0.14
    - kubernetes==28.1.0
    - cookiecutter
    - boto3
    - botocore
    - pystac
    - python-dotenv
    - pyjwt
